format = """
$directory\
$git_branch\
$kubernetes\
$python\
$line_break\
$character
"""

add_newline = false

[directory]
format = "[$path]($style) "
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style) "
style = "bold blue"

[kubernetes]
disabled = false
format = "[k8s:$context/$namespace]($style) "
style = "bold purple"

[python]
format = '[\($virtualenv\)]($style) '
style = "bold yellow"
detect_extensions = []
detect_files = []
detect_folders = []
[line_break]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
format = "$symbol "
